### PR TITLE
App cleanup

### PR DESCRIPTION
**Pull request by SKevo18**
- Use [routers](https://fastapi.tiangolo.com/tutorial/bigger-applications/#apirouter) to make the application more scalable
- Use `.py` file instead of JSON - I am not sure whether you want this, but it allows you to import settings more easily
  - `private_settings.py` for sensitive settings, not to be commited
- New endpoints:
  - Strings
    - Uppercase, lowercase
    - Similarity percentage
    - Replace with
    - Split
  - 8 ball
- All routers now use a standarized JSON response format both for successful and error-ish responses, for consistency across the API
- Fixed some code to make it more simple and straighforward (while adding some more complex things)
- And many other little tweaks

This is my first pull request, and I am not sure what your vision with this app is or what is your code style, so feel free to adapt it to your needs. I am thinking of becoming a regular contributor to this project, and expanding it.

You're quite young, but you have a lot of potential and I love the enthusiasm, so you have my respect! Do you maybe have a Discord so we can keep in touch, should you be interested in some of my ideas?

### CODE REVIEW

**Comment by cobaltgit** [comment]
cobalt#9144 is my Discord. There's a bunch of conflicts I need to resolve before merging however

**Comment by cobaltgit** [comment]
I also apologise for not noticing this pull request earlier

**Comment by cobaltgit** [comment]
Would the exception handler be able to catch other status codes?

**Comment by cobaltgit** [comment]
And with such changes I might be able to make the API compatible with Python 3.8

**Comment by SKevo18** [comment]
> cobalt#9144 is my Discord. There's a bunch of conflicts I need to resolve before merging however
> I also apologise for not noticing this pull request earlier

That's okay 👍 However, I can't send you friend request, maybe because of your privacy settings. My Discord is `Kevo#7590` BTW

> Would the exception handler be able to catch other status codes?

If you mean this one: https://github.com/cobaltgit/CobaltAPI/pull/1/files#diff-69f5bce0a035ebacf30bd0f1d9ae5d18919e729789eb1a6a0cbe827f1877cdc5R57-R68

...then it catches all `HTTPException` and `RequestValidationError`, which should cover most FastAPI exceptions. It then returns an error message with the `400` status code (Bad Request). It is very generic however, and I am not sure if it catches absolutely all errors

> And with such changes I might be able to make the API compatible with Python 3.8

I haven't had a look at your current code, but this pull should be compatible with 3.6+ (I tested it with either 3.9 or 3.10, can't remember, but it worked fine)

**Comment by cobaltgit** [comment]
I'll test on both 3.6 and 3.8 if you insist

**Comment by cobaltgit** [comment]
I'll have to close this and then push it myself as there's loads of conflicts here. Thanks

**Comment by cobaltgit** [comment]
Can't really set up the virtualenv, but I'm certain it should work on 3.8+ (aiohttp constraint)

**Comment by cobaltgit** [comment]
Testing seems to be going well

**Pull request closed without merging**
